In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('ner_datasetreference.csv', encoding='ISO-8859-1')
df.head()

    Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [42]:
#return a Pandas Series with counts of unique words in the 'Word' column 
df['Word'].value_counts()

the         52573
.           47761
,           32754
of          26354
in          26323
            ...
Dateline        1
ISRO            1
G.              1
Madhavan        1
Bermel          1
Name: Word, Length: 35178, dtype: int64

In [58]:
#create a new column 'Dateline' and set it to 1 for rows where the 'Word' column is equal to 'Dateline' and 0 otherwise
df['Dateline'] = df['Word'].apply(lambda x: 1 if x =='Dateline' else 0)

In [59]:
#number of rows and the number of columns.
df.shape

(1048575, 6)

In [60]:
df.head(20)

     Sentence #           Word  POS    Tag  IN  Dateline
0   Sentence: 1      Thousands  NNS      O   0         0
1           NaN             of   IN      O   1         0
2           NaN  demonstrators  NNS      O   0         0
3           NaN           have  VBP      O   0         0
4           NaN        marched  VBN      O   0         0
5           NaN        through   IN      O   1         0
6           NaN         London  NNP  B-geo   0         0
7           NaN             to   TO      O   0         0
8           NaN        protest   VB      O   0         0
9           NaN            the   DT      O   0         0
10          NaN            war   NN      O   0         0
11          NaN             in   IN      O   1         0
12          NaN           Iraq  NNP  B-geo   0         0
13          NaN            and   CC      O   0         0
14          NaN         demand   VB      O   0         0
15          NaN            the   DT      O   0         0
16          NaN     withdrawal   NN      O   0         0
17          NaN             of   IN      O   1         0
18          NaN        British   JJ  B-gpe   0         0
19          NaN         troops  NNS      O   0         0

In [80]:
#Train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Word'], df['Dateline'], test_size=0.2)

In [81]:
print(X_train.shape)

(838860,)

In [63]:
X_test.shape

(209715,)

In [64]:
type(X_train)

pandas.core.series.Series

In [65]:
X_train[:4]

487665           are
602821         Sudan
274658    cease-fire
539951    restarting
Name: Word, dtype: object

In [66]:
type(y_train)

pandas.core.series.Series

In [67]:
y_train[:4]

487665    0
602821    0
274658    0
539951    0
Name: IN, dtype: int64

In [68]:
type(X_train.values)

numpy.ndarray

In [69]:
# Create bag of words representation using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<838860x25709 sparse matrix of type '<class 'numpy.int64'>'
	with 744671 stored elements in Compressed Sparse Row format>

In [70]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [71]:
X_train_cv.shape

(838860, 25709)

In [72]:
v.get_feature_names_out()[1771]

'ancient'

In [73]:
v.vocabulary_

{'are': 2099,
 'sudan': 22406,
 'cease': 4407,
 'fire': 9026,
 'restarting': 19504,
 'states': 22042,
 'apology': 1969,
 'bowman': 3706,
 '160': 127,
 'an': 1744,
 'aristide': 2131,
 'the': 23170,
 'with': 25233,
 'reporter': 19360,
 'official': 16362,
 'after': 1305,
 'before': 3065,
 'it': 12182,
 'president': 17964,
 'earlier': 7613,
 'tribal': 23705,
 'villagers': 24661,
 'this': 23233,
 'says': 20390,
 'day': 6276,
 'has': 10640,
 'christians': 4789,
 'aging': 1341,
 'trains': 23592,
 'still': 22123,
 'africa': 1296,
 'international': 11980,
 'iraqi': 12102,
 'presidential': 17965,
 'war': 24899,
 'thursday': 23288,
 'early': 7615,
 'justice': 12587,
 'in': 11539,
 'israel': 12167,
 'replace': 19347,
 'ministers': 14984,
 'movement': 15382,
 'where': 25108,
 'final': 8983,
 '1994': 360,
 'they': 23207,
 'exclusive': 8392,
 'ugandan': 23956,
 'friday': 9455,
 'denver': 6598,
 'ordered': 16531,
 'have': 10682,
 'reporters': 19361,
 'aircraft': 1407,
 'were': 25069,
 'there': 23196,
 'participate': 16990,
 'relief': 19219,
 'officials': 16364,
 'at': 2368,
 'prepares': 17941,
 'ricardo': 19672,
 'authorities': 2500,
 'increased': 11606,
 '10': 21,
 'flexibility': 9132,
 'expressed': 8530,
 'shrinking': 21130,
 'relation': 19192,
 'provincial': 18280,
 'target': 22896,
 'gerhard': 9800,
 'was': 24942,
 'jets': 12403,
 'calm': 4090,
 'tanith': 22870,
 'american': 1690,
 'aggressive': 1333,
 'purposes': 18391,
 'open': 16461,
 'four': 9351,
 'group': 10176,
 'did': 6858,
 'emile': 7894,
 'new': 15903,
 'said': 20172,
 'request': 19399,
 'estimated': 8252,
 'basic': 2934,
 'federally': 8838,
 'muslim': 15529,
 'inhabited': 11772,
 'for': 9242,
 'plant': 17536,
 'medical': 14652,
 'radar': 18588,
 'although': 1635,
 'of': 16341,
 'be': 3007,
 'possible': 17789,
 'per': 17217,
 'by': 4024,
 'negotiations': 15836,
 'coalition': 5013,
 'his': 10982,
 'chinese': 4729,
 'baseless': 2927,
 'outbreak': 16641,
 'number': 16193,
 'first': 9054,
 'say': 20385,
 'speaker': 21765,
 'mr': 15402,
 'korean': 13084,
 'hersh': 10887,
 'found': 9344,
 'intention': 11937,
 'central': 4454,
 'almost': 1605,
 'health': 10736,
 'from': 9478,
 'issue': 12177,
 'news': 15917,
 'pattle': 17088,
 'out': 16638,
 'to': 23385,
 'but': 4002,
 'ventures': 24547,
 'kurdish': 13175,
 'enclosed': 7964,
 'among': 1720,
 'no': 16037,
 'uzbeks': 24409,
 'suspected': 22625,
 'tournament': 23522,
 'brief': 3805,
 'wounded': 25332,
 'near': 15795,
 'ex': 8345,
 'prime': 18029,
 'praised': 17857,
 'import': 11502,
 'summit': 22491,
 'on': 16435,
 'during': 7571,
 'up': 24309,
 'insurgent': 11905,
 'years': 25459,
 'killing': 12952,
 'and': 1772,
 'endorsed': 7995,
 'stop': 22164,
 'conditions': 5387,
 'than': 23154,
 'intermittent': 11977,
 'march': 14321,
 'cpp': 5878,
 'development': 6794,
 'will': 25168,
 'ashore': 2254,
 'carried': 4266,
 '15': 108,
 'seats': 20566,
 'nepal': 15862,
 'killed': 12950,
 'under': 24060,
 'focus': 9200,
 'neighborhood': 15842,
 'told': 23410,
 'interior': 11970,
 '2010': 383,
 'dick': 6852,
 'leading': 13450,
 'called': 4085,
 'is': 12135,
 'left': 13497,
 'suspect': 22624,
 '65': 695,
 '000': 1,
 'century': 4466,
 'market': 14374,
 'town': 23535,
 'stalls': 21988,
 'provides': 18275,
 'black': 3385,
 'others': 16611,
 'statement': 22040,
 'massive': 14480,
 'michael': 14837,
 're': 18819,
 'established': 8242,
 'may': 14554,
 'hands': 10520,
 'delhi': 6497,
 'charges': 4590,
 'been': 3061,
 'known': 13034,
 'inmates': 11805,
 'exchange': 8381,
 'not': 16127,
 'its': 12195,
 'back': 2635,
 'spaceshipone': 21732,
 'process': 18097,
 'radio': 18598,
 '1967': 328,
 'virus': 24699,
 'polls': 17689,
 'department': 6604,
 'only': 16449,
 'militants': 14908,
 'reports': 19363,
 'least': 13474,
 'unemployment': 24126,
 'french': 9438,
 'general': 9736,
 'six': 21329,
 'falling': 8670,
 'saving': 20375,
 'rebels': 18889,
 'deploying': 6627,
 'officers': 16360,
 'over': 16704,
 'three': 23253,
 'nuclear': 16186,
 'italy': 12187,
 'program': 18141,
 'rally': 18678,
 'injuries': 11797,
 'continue': 5612,
 'government': 10019,
 'all': 1556,
 'attack': 2410,
 'council': 5801,
 'lending': 13542,
 'national': 15726,
 'forum': 9329,
 'some': 21637,
 'those': 23240,
 'move': 15380,
 'problems': 18088,
 'school': 20448,
 '19': 258,
 'more': 15272,
 'congolese': 5454,
 'won': 25271,
 'fighting': 8948,
 'russian': 20045,
 'between': 3250,
 'relations': 19193,
 'agency': 1322,
 'proportionately': 18207,
 'supporters': 22548,
 'denied': 6575,
 'pour': 17827,
 'venezuelan': 24540,
 'saturday': 20359,
 'women': 25270,
 'globalization': 9919,
 'recruitment': 18999,
 'son': 21646,
 'iran': 12098,
 'eta': 8260,
 'creation': 5911,
 'time': 23339,
 'budget': 3893,
 'blasts': 3428,
 'infected': 11705,
 'comments': 5192,
 'bombing': 3576,
 'minister': 14982,
 'people': 17210,
 'witnesses': 25251,
 'date': 6250,
 'sunday': 22504,
 'racism': 18581,
 '60': 674,
 'elections': 7795,
 'declared': 6367,
 'khan': 12859,
 'abubakar': 953,
 'southern': 21708,
 'baku': 2731,
 'tbilisi': 22958,
 'ceyhan': 4495,
 'interpol': 11986,
 'saying': 20388,
 'helped': 10822,
 'barrel': 2896,
 'florida': 9161,
 '76': 743,
 'decision': 6358,
 'control': 5648,
 'criticism': 5964,
 'he': 10713,
 'field': 8930,
 'could': 5800,
 'july': 12549,
 'would': 25330,
 'caused': 4373,
 'au': 2451,
 'what': 25095,
 'internationally': 11982,
 'communication': 5224,
 'bolivia': 3553,
 'opera': 16469,
 'fails': 8645,
 'later': 13375,
 'bomb': 3567,
 'monitoring': 15214,
 'pirate': 17482,
 'other': 16610,
 'that': 23167,
 'ships': 21042,
 'olmert': 16412,
 'appeals': 1983,
 'direct': 6933,
 'dead': 6293,
 'state': 22037,
 'kiev': 12940,
 'aid': 1382,
 'week': 25031,
 'petroleum': 17335,
 'expelled': 8464,
 'arrived': 2183,
 'cargo': 4237,
 'also': 1620,
 'days': 6282,
 'recall': 18901,
 'washington': 24947,
 'areas': 2101,
 'tymoshenko': 23916,
 'al': 1464,
 'mutairi': 15540,
 'who': 25129,
 'based': 2926,
 'convicted': 5680,
 'project': 18152,
 '2002': 373,
 'we': 24994,
 'being': 3092,
 'vasil': 24498,
 'mike': 14888,
 'midler': 14866,
 'suicide': 22449,
 'campaign': 4118,
 'lawsuits': 13425,
 'karrada': 12718,
 'starring': 22025,
 'print': 18044,
 'meeting': 14671,
 'johanns': 12463,
 'border': 3621,
 'softer': 21572,
 'term': 23093,
 'hamas': 10462,
 'allegations': 1563,
 'future': 9555,
 'offensive': 16351,
 'leaders': 13448,
 'then': 23185,
 'crossing': 5992,
 'representatives': 19370,
 'paintings': 16855,
 'renounce': 19296,
 'torture': 23486,
 'sanctions': 20278,
 'secretary': 20588,
 'rich': 19675,
 'stronghold': 22282,
 'married': 14399,
 'made': 14054,
 'year': 25455,
 'officer': 16359,
 'january': 12318,
 'widespread': 25146,
 'victory': 24621,
 'united': 24194,
 'private': 18062,
 'million': 14932,
 'assassination': 2297,
 'details': 6746,
 'postponed': 17801,
 'death': 6313,
 'last': 13366,
 'information': 11750,
 'leftist': 13498,
 'decisions': 6359,
 'congress': 5463,
 'palestinian': 16879,
 'driven': 7468,
 'inappropriate': 11551,
 '2001': 372,
 'shipments': 21039,
 'defendants': 6424,
 'plea': 17569,
 'british': 3829,
 'kalameh': 12635,
 '13': 76,
 'adopted': 1190,
 'afghanistan': 1288,
 '40': 562,
 'avenging': 2534,
 'indian': 11636,
 'sun': 22498,
 'newspapers': 15922,
 'pennetta': 17200,
 'passing': 17035,
 'line': 13702,
 'return': 19581,
 'exports': 8523,
 'against': 1314,
 'political': 17677,
 'voted': 24776,
 'networks': 15887,
 'abuses': 963,
 'often': 16373,
 'himalayan': 10954,
 'customized': 6102,
 'record': 18975,
 'months': 15242,
 'stories': 22178,
 'hassan': 10651,
 'eu': 8280,
 'them': 23179,
 'workers': 25299,
 'since': 21270,
 'soldiers': 21597,
 'tank': 22871,
 'province': 18278,
 'october': 16327,
 'san': 20269,
 'society': 21559,
 'forces': 9254,
 'beijing': 3089,
 'detonated': 6775,
 'pirates': 17483,
 'hubble': 11214,
 'ask': 2267,
 'military': 14916,
 'two': 23911,
 'forms': 9312,
 'taleban': 22828,
 'means': 14611,
 'understanding': 24099,
 'reinstatement': 19170,
 'today': 23390,
 'affect': 1265,
 'commissioner': 5201,
 'announced': 1870,
 'nairobi': 15636,
 'indicate': 11640,
 'reservoir': 19435,
 'her': 10854,
 'family': 8688,
 'step': 22095,
 'zenawi': 25632,
 'moscow': 15306,
 'bank': 2816,
 'brussels': 3875,
 'greek': 10103,
 'instead': 11872,
 'america': 1689,
 'flight': 9135,
 'station': 22046,
 'mosul': 15322,
 'informed': 11751,
 'account': 1015,
 'arrests': 2179,
 'commission': 5199,
 'newspaper': 15921,
 'nicolas': 15966,
 'murder': 15491,
 'come': 5157,
 'site': 21319,
 'industry': 11686,
 'consulate': 5555,
 'beginning': 3072,
 'run': 20024,
 'better': 3246,
 'water': 24967,
 'drug': 7487,
 'tuesday': 23821,
 'as': 2225,
 'believed': 3123,
 'countries': 5830,
 'producer': 18112,
 'piot': 17474,
 'off': 16343,
 'charged': 4587,
 'court': 5849,
 'blow': 3483,
 'largest': 13348,
 'effort': 7741,
 'peace': 17129,
 'you': 25508,
 'adjourned': 1155,
 'treat': 23678,
 'impact': 11466,
 'volcano': 24745,
 'deal': 6302,
 'deputy': 6650,
 'when': 25105,
 'airplanes': 1425,
 'miers': 14875,
 'jailed': 12262,
 'roadside': 19783,
 'greenhouse': 10109,
 'opposition': 16498,
 '94': 807,
 'mozambique': 15397,
 'non': 16062,
 'saddam': 20117,
 'came': 4104,
 'shepherd': 20988,
 'any': 1943,
 'seized': 20648,
 'formally': 9302,
 'torn': 23475,
 'targeting': 22898,
 'postpone': 17800,
 'around': 2165,
 'assurances': 2348,
 'protested': 18252,
 'interviewer': 12016,
 'birds': 3357,
 'loss': 13891,
 'song': 21648,
 'about': 925,
 'level': 13596,
 'barrels': 2899,
 'power': 17833,
 'samples': 20264,
 'informer': 11752,
 'loud': 13898,
 'approved': 2028,
 'country': 5831,
 'confiscated': 5435,
 'japanese': 12321,
 'occurred': 16317,
 'chairman': 4513,
 'demolished': 6551,
 'point': 17637,
 'visiting': 24709,
 'india': 11635,
 'banks': 2823,
 'crisis': 5957,
 'implement': 11489,
 'jail': 12260,
 'jewish': 12410,
 'joy': 12516,
 'commerce': 5193,
 'doctors': 7245,
 'armored': 2155,
 'wealth': 25005,
 'airstrike': 1430,
 'graz': 10091,
 'ban': 2784,
 'senior': 20700,
 'viktor': 24656,
 'mccormack': 14587,
 'koizumi': 13051,
 '1980': 343,
 'meet': 14670,
 'failed': 8643,
 'ago': 1344,
 'rating': 18772,
 'role': 19858,
 'usage': 24369,
 'haifa': 10403,
 'building': 3917,
 'disputed': 7109,
 'potential': 17813,
 'monitor': 15212,
 'lack': 13232,
 'losses': 13892,
 'smoking': 21498,
 'israeli': 12168,
 'former': 9307,
 'weeks': 25036,
 'terror': 23111,
 'credit': 5921,
 'west': 25075,
 'suspects': 22626,
 'including': 11585,
 'start': 22027,
 'report': 19357,
 '200': 369,
 'customs': 6103,
 'signs': 21216,
 'controls': 5653,
 '300': 498,
 'member': 14716,
 'name': 15652,
 'aide': 1384,
 'strongly': 22284,
 'replacing': 19351,
 'threat': 23247,
 'release': 19206,
 'iraq': 12101,
 'held': 10803,
 'fish': 9058,
 'custody': 6099,
 'nations': 15741,
 'capital': 4182,
 'emergency': 7886,
 'severe': 20804,
 'operation': 16475,
 'video': 24623,
 'positions': 17778,
 'world': 25309,
 'tensions': 23080,
 'andaman': 1773,
 'taya': 22949,
 'eggs': 7751,
 'seeking': 20623,
 'lebanon': 13483,
 'age': 1318,
 'travel': 23660,
 '59': 668,
 'included': 11583,
 'chirac': 4740,
 'soft': 21567,
 'economic': 7668,
 'reach': 18820,
 'unable': 24003,
 'strike': 22256,
 'savigny': 20372,
 'sur': 22565,
 'orge': 16556,
 'expected': 8454,
 'began': 3067,
 'fires': 9042,
 'oil': 16385,
 'razak': 18807,
 'security': 20606,
 'election': 7794,
 'condemns': 5383,
 'because': 3040,
 'ministry': 14986,
 'egypt': 7752,
 'gaza': 9699,
 'vote': 24775,
 'transmission': 23632,
 'tunnel': 23846,
 'handed': 10503,
 'los': 13886,
 'ends': 8003,
 'carrying': 4274,
 'shop': 21073,
 'weapons': 25011,
 'until': 24286,
 'baghdad': 2680,
 'deaths': 6314,
 'one': 16441,
 'zawahiri': 25614,
 'rodina': 19837,
 'bailouts': 2705,
 'third': 23227,
 'released': 19207,
 'ongoing': 16444,
 'urging': 24356,
 'scrapped': 20505,
 'their': 23178,
 'shareholders': 20915,
 '588': 666,
 'white': 25122,
 'down': 7371,
 'center': 4448,
 'protection': 18239,
 'ibrahim': 11336,
 'according': 1011,
 'inspector': 11854,
 'senator': 20690,
 'issues': 12179,
 'human': 11231,
 'following': 9219,
 'now': 16172,
 'debt': 6327,
 'reza': 19653,
 'driving': 7472,
 'shops': 21080,
 'rescuers': 19417,
 'arrest': 2176,
 'hearing': 10743,
 'resulted': 19531,
 'working': 25303,
 'union': 24183,
 'honduran': 11072,
 'wounding': 25333,
 'basis': 2942,
 'ugly': 23958,
 'or': 16512,
 'rangin': 18728,
 'house': 11177,
 'police': 17664,
 'nearly': 15800,
 '31st': 507,
 'le': 13445,
 'submerged': 22346,
 'whether': 25112,
 'prison': 18054,
 'do': 7237,
 'korea': 13083,
 'safe': 20145,
 'togolese': 23399,
 'flagged': 9084,
 '1829': 206,
 'repeatedly': 19339,
 'into': 12027,
 'militant': 14907,
 'approach': 2018,
 'support': 22545,
 'hypothermia': 11318,
 'discuss': 7030,
 'hour': 11174,
 'balad': 2735,
 'battle': 2977,
 'efforts': 7742,
 'uruguay': 24363,
 'session': 20780,
 'members': 14717,
 'long': 13853,
 'army': 2161,
 'turn': 23877,
 'kian': 12913,
 'allowed': 1592,
 'greeted': 10114,
 'rights': 19716,
 'assist': 2328,
 'island': 12157,
 'sectarian': 20593,
 'civilian': 4871,
 'investigators': 12067,
 'range': 18723,
 'russia': 20044,
 'cairo': 4062,
 'ruled': 20011,
 'ray': 18802,
 'high': 10912,
 'avoid': 2553,
 'saeed': 20138,
 'asia': 2261,
 'de': 6289,
 'fled': 9118,
 'leaving': 13480,
 'mid': 14857,
 '2006': 377,
 'bases': 2929,
 'stability': 21950,
 'parts': 17011,
 'emerging': 7888,
 'headquarters': 10729,
 'el': 7779,
 'arish': 2129,
 'light': 13664,
 'insurgents': 11906,
 'torgelow': 23473,
 'recent': 18919,
 'negotiator': 15837,
 'blair': 3404,
 'unidentified': 24164,
 'euro': 8286,
 'publicly': 18318,
 'completely': 5293,
 'seek': 20620,
 'tight': 23318,
 'habit': 10362,
 'rely': 19234,
 'colonists': 5120,
 'mother': 15325,
 'ambassador': 1665,
 'dutch': 7579,
 'immigration': 11454,
 'confirm': 5429,
 'without': 25246,
 'nationals': 15740,
 'middle': 14860,
 'journalists': 12507,
 'mofaz': 15147,
 '27': 468,
 'visa': 24701,
 'mission': 15059,
 'charities': 4595,
 'disapprove': 6970,
 'videotaped': 24627,
 'highest': 10914,
 'constant': 5532,
 'burning': 3969,
 'foreign': 9265,
 'millions': 14934,
 'backed': 2639,
 '2000': 370,
 'biological': 3348,
 'died': 6862,
 'systems': 22746,
 'cleanup': 4926,
 'special': 21774,
 'plot': 17590,
 'tried': 23722,
 'miller': 14927,
 'currently': 6087,
 'committed': 5209,
 'australia': 2487,
 'above': 927,
 'these': 23205,
 'abducted': 868,
 'implementation': 11490,
 'madrid': 14070,
 'successfully': 22394,
 'cape': 4180,
 'financial': 8994,
 'bay': 2991,
 'opec': 16459,
 'anesthesia': 1805,
 'syria': 22740,
 'valenzuela': 24447,
 'wreckage': 25350,
 'xinhua': 25392,
 'exporting': 8522,
 'fatah': 8757,
 'wednesday': 25028,
 'threw': 23256,
 'eastern': 7643,
 'length': 13546,
 'providing': 18276,
 'abusing': 964,
 'tv': 23900,
 'major': 14144,
 'conduct': 5398,
 'which': 25114,
 'press': 17971,
 'fracture': 9366,
 'subject': 22339,
 'denies': 6577,
 'another': 1888,
 'bush': 3988,
 'importunities': 11510,
 'bilfinger': 3317,
 'footed': 9237,
 'both': 3659,
 'agents': 1326,
 'warming': 24915,
 'kim': 12961,
 'so': 21543,
 'shi': 21002,
 'ite': 12189,
 'questioned': 18525,
 'nobel': 16039,
 'malaysian': 14178,
 'raised': 18658,
 'haitian': 10421,
 'depends': 6614,
 'claims': 4881,
 'stroke': 22273,
 'region': 19117,
 'qaida': 18430,
 'cookstown': 5694,
 'partnership': 17007,
 'vaccinate': 24416,
 'protesting': 18255,
 'stressed': 22243,
 'league': 13453,
 'additional': 1126,
 'illegitimate': 11418,
 'limited': 13692,
 'packages': 16821,
 'employees': 7924,
 'shows': 21123,
 'afghan': 1285,
 'tear': 22975,
 'top': 23451,
 'europe': 8287,
 'had': 10374,
 'conflict': 5438,
 'take': 22811,
 'raza': 18806,
 '18': 184,
 'bordering': 3623,
 'media': 14643,
 'peacekeeping': 17135,
 'husband': 11278,
 'next': 15925,
 'sharon': 20931,
 'entered': 8071,
 'products': 18120,
 'complete': 5291,
 '06': 12,
 'jan': 12302,
 'jet': 12401,
 'reported': 19358,
 'catholics': 4359,
 'searches': 20555,
 'end': 7978,
 'same': 20252,
 'race': 18574,
 'highly': 10920,
 'trade': 23562,
 'h5n1': 10350,
 'represents': 19373,
 'each': 7606,
 'sponsored': 21873,
 'mine': 14956,
 'restore': 19513,
 'weather': 25017,
 'amid': 1702,
 'upper': 24326,
 'appealing': 1982,
 'conference': 5410,
 'accident': 992,
 'encounter': 7967,
 'remains': 19240,
 'borders': 3624,
 'bombings': 3577,
 'see': 20614,
 'plagued': 17516,
 'recognize': 18946,
 'statistics': 22056,
 'wo': 25260,
 'downer': 7374,
 'mientes': 14874,
 'restrictions': 19523,
 'yaracuy': 25436,
 'second': 20580,
 'men': 14731,
 'place': 17508,
 'outlaw': 16660,
 'genocide': 9758,
 'attackers': 2413,
 'cases': 4297,
 'knew': 13021,
 'medieval': 14659,
 'syvkovych': 22747,
 'companies': 5240,
 'yemeni': 25467,
 'attacks': 2415,
 'oman': 16424,
 'teachers': 22966,
 'hugo': 11226,
 'unnecessary': 24232,
 'rising': 19748,
 'local': 13809,
 'osama': 16585,
 'legal': 13504,
 'already': 1619,
 'beaten': 3028,
 'close': 4976,
 'trip': 23740,
 'criticized': 5967,
 'shown': 21122,
 'arctic': 2097,
 'japan': 12320,
 'player': 17558,
 'sources': 21702,
 'manslaughter': 14283,
 'several': 20802,
 'albanians': 1489,
 'bail': 2702,
 'leader': 13447,
 'latin': 13383,
 'framework': 9383,
 'money': 15206,
 'own': 16795,
 'reuters': 19592,
 'word': 25291,
 'waivers': 24846,
 '28': 476,
 'old': 16400,
 'allow': 1590,
 'meanwhile': 14614,
 'injuring': 11798,
 'burma': 3964,
 'monitors': 15215,
 'change': 4555,
 'month': 15240,
 'cut': 6104,
 'angola': 1826,
 'divided': 7197,
 'troubled': 23764,
 'pakistan': 16865,
 'pope': 17725,
 'weaken': 24998,
 'concern': 5353,
 'believes': 3126,
 'chancellor': 4544,
 'nine': 16003,
 '70': 714,
 'city': 4867,
 'canary': 4137,
 'prosecution': 18220,
 'along': 1610,
 'event': 8316,
 'while': 25116,
 'capacity': 4179,
 'raid': 18636,
 'baiji': 2699,
 'economy': 7674,
 'party': 17012,
 'promoter': 18179,
 ...}

In [74]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [75]:
np.where(X_train_np[0]!=0)

(array([2099]),)

In [76]:
X_train_np[0][1771]

0

In [77]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [78]:
X_test_cv = v.transform(X_test)

In [79]:
from sklearn.metrics import classification_report

import numpy as np
# predicted = 0,1
predicted = model.predict(X_train_cv )

# accuracy
print(np.mean(predicted == y_test ))

/var/folders/mk/0wr72hyx31d9dtn7r75t45y40000gn/T/ipykernel_28590/2000389303.py:8: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(np.mean(predicted == y_test ))

ValueError: ('Lengths must match to compare', (209715,), (838860,))